services:

  setup:
    image: fredjk/threat-hunting-elk-stack:setup-${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,delegated
      - ./setup/lib.sh:/lib.sh:ro
      - ./setup/roles:/roles:ro
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch
    profiles:
      - setup

  elasticsearch:
    image: fredjk/threat-hunting-elk-stack:elasticsearch-${ELASTIC_VERSION}
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elk
    restart: unless-stopped

  kibana:
    image: fredjk/threat-hunting-elk-stack:kibana-${ELASTIC_VERSION}
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    environment:
      - KIBANA_SYSTEM_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
    networks:
      - elk
    restart: unless-stopped

#  backend:
#    image: fredjk/threat-hunting-backend:django-backend
#    container_name: backend
#    depends_on:
#      - elasticsearch
#    environment:
#      - SECRET_KEY=${SECRET_KEY}
#      - DEBUG=${DEBUG}
#      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
#    ports:
#      - 8000:8000
#    volumes:
#      - static_volume:/app/static
#    networks:
#      - elk
#    restart: unless-stopped

networks:
  elk:
    driver: bridge

env_file:
  - .env

volumes:
  elasticsearch_data:
  static_volume: