
winlogbeat.event_logs:
  - name: Microsoft-Windows-Sysmon/Operational
    event_id: 3

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "http://34.67.212.1:5601"

output.elasticsearch:
  hosts: ["34.67.212.1:9200"]
  pipeline: "winlogbeat-%{[agent.version]}-routing"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
