name: Build Frontend Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REPO: 'threat-hunting-frontend'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ransomware-hunter

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/ransomware-hunter
          file: ./frontend/ransomware-hunter/Dockerfile
          # Conditionally push the image when code is merged to main
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          # Load the image locally when building during PRs
          load: ${{ !(github.event_name == 'push' && github.ref == 'refs/heads/main') }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO }}:latest